from datetime import time

symbols_macro = [
    {
        "ID": 1,
        "GROUP": "Index",
        "NAME": "S&P 500",
        "SYMBOL": "^GSPC",
        "EXCHANGE": "Yahoo",
        "PLATFORM": "Yahoo",
        "BROKER": "Yahoo",
        "CCY": "USD",
        "TIMEZONE": "America/New_York",
        "TRADE_STARTS": time(0, 0, 0),
        "TRADE_ENDS": time(23, 59, 59)
    },
    {
        "ID": 2,
        "GROUP": "Index",
        "NAME": "Dow 30",
        "SYMBOL": "^DJI",
        "EXCHANGE": "Yahoo",
        "PLATFORM": "Yahoo",
        "BROKER": "Yahoo",
        "CCY": "USD",
        "TIMEZONE": "America/New_York",
        "TRADE_STARTS": time(0, 0, 0),
        "TRADE_ENDS": time(23, 59, 59)
    },
    {
        "ID": 3,
        "GROUP": "Index",
        "NAME": "Nasdaq 100",
        "SYMBOL": "^NDX",
        "EXCHANGE": "Yahoo",
        "PLATFORM": "Yahoo",
        "BROKER": "Yahoo",
        "CCY": "USD",
        "TIMEZONE": "America/New_York",
        "TRADE_STARTS": time(0, 0, 0),
        "TRADE_ENDS": time(23, 59, 59)
    },
    {
        "ID": 4,
        "GROUP": "Index",
        "NAME": "Russell 2000",
        "SYMBOL": "^RUT",
        "EXCHANGE": "Yahoo",
        "PLATFORM": "Yahoo",
        "BROKER": "Yahoo",
        "CCY": "USD",
        "TIMEZONE": "America/New_York",
        "TRADE_STARTS": time(0, 0, 0),
        "TRADE_ENDS": time(23, 59, 59)
    },
    {
        "ID": 5,
        "GROUP": "Index",
        "NAME": "VIX",
        "SYMBOL": "^VIX",
        "EXCHANGE": "Yahoo",
        "PLATFORM": "Yahoo",
        "BROKER": "Yahoo",
        "CCY": "USD",
        "TIMEZONE": "America/Chicago",
        "TRADE_STARTS": time(0, 0, 0),
        "TRADE_ENDS": time(23, 59, 59)
    },
    {
        "ID": 6,
        "GROUP": "Index",
        "NAME": "FTSE 100",
        "SYMBOL": "^FTSE",
        "EXCHANGE": "Yahoo",
        "PLATFORM": "Yahoo",
        "BROKER": "Yahoo",
        "CCY": "GBP",
        "TIMEZONE": "Europe/London",
        "TRADE_STARTS": time(0, 0, 0),
        "TRADE_ENDS": time(23, 59, 59)
    },
    {
        "ID": 7,
        "GROUP": "Index",
        "NAME": "Euronext 100",
        "SYMBOL": "^N100",
        "EXCHANGE": "Yahoo",
        "PLATFORM": "Yahoo",
        "BROKER": "Yahoo",
        "CCY": "EUR",
        "TIMEZONE": "Europe/Amsterdam",
        "TRADE_STARTS": time(0, 0, 0),
        "TRADE_ENDS": time(23, 59, 59)
    },
    {
        "ID": 8,
        "GROUP": "Index",
        "NAME": "DAX 40",
        "SYMBOL": "^GDAXI",
        "EXCHANGE": "Yahoo",
        "PLATFORM": "Yahoo",
        "BROKER": "Yahoo",
        "CCY": "EUR",
        "TIMEZONE": "Europe/Berlin",
        "TRADE_STARTS": time(0, 0, 0),
        "TRADE_ENDS": time(23, 59, 59)
    },
    {
        "ID": 9,
        "GROUP": "Index",
        "NAME": "CAC 40",
        "SYMBOL": "^FCHI",
        "EXCHANGE": "Yahoo",
        "PLATFORM": "Yahoo",
        "BROKER": "Yahoo",
        "CCY": "EUR",
        "TIMEZONE": "Europe/Paris",
        "TRADE_STARTS": time(0, 0, 0),
        "TRADE_ENDS": time(23, 59, 59)
    },
    {
        "ID": 10,
        "GROUP": "Index",
        "NAME": "Nikkei 225",
        "SYMBOL": "^N225",
        "EXCHANGE": "Yahoo",
        "PLATFORM": "Yahoo",
        "BROKER": "Yahoo",
        "CCY": "JPY",
        "TIMEZONE": "Asia/Tokyo",
        "TRADE_STARTS": time(0, 0, 0),
        "TRADE_ENDS": time(23, 59, 59)
    },
    {
        "ID": 11,
        "GROUP": "Index",
        "NAME": "SSE Composite",
        "SYMBOL": "000001.SS",
        "EXCHANGE": "Yahoo",
        "PLATFORM": "Yahoo",
        "BROKER": "Yahoo",
        "CCY": "CNY",
        "TIMEZONE": "Asia/Shanghai",
        "TRADE_STARTS": time(0, 0, 0),
        "TRADE_ENDS": time(23, 59, 59)
    },
    {
        "ID": 12,
        "GROUP": "Index",
        "NAME": "Ibovespa",
        "SYMBOL": "^BVSP",
        "EXCHANGE": "Yahoo",
        "PLATFORM": "Yahoo",
        "BROKER": "Yahoo",
        "CCY": "BRL",
        "TIMEZONE": "America/Sao_Paulo",
        "TRADE_STARTS": time(0, 0, 0),
        "TRADE_ENDS": time(23, 59, 59)
    },
    {
        "ID": 13,
        "GROUP": "Commodity",
        "NAME": "Bitcoin",
        "SYMBOL": "BTC-USD",
        "EXCHANGE": "Yahoo",
        "PLATFORM": "Yahoo",
        "BROKER": "Yahoo",
        "CCY": "USD",
        "TIMEZONE": "UTC",
        "TRADE_STARTS": time(0, 0, 0),
        "TRADE_ENDS": time(23, 59, 59)
    },
    {
        "ID": 14,
        "GROUP": "Commodity",
        "NAME": "Gold",
        "SYMBOL": "GC=F",
        "EXCHANGE": "Yahoo",
        "PLATFORM": "Yahoo",
        "BROKER": "Yahoo",
        "CCY": "USD",
        "TIMEZONE": "America/New_York",
        "TRADE_STARTS": time(0, 0, 0),
        "TRADE_ENDS": time(23, 59, 59)
    },
    {
        "ID": 15,
        "GROUP": "Commodity",
        "NAME": "Silver",
        "SYMBOL": "SI=F",
        "EXCHANGE": "Yahoo",
        "PLATFORM": "Yahoo",
        "BROKER": "Yahoo",
        "CCY": "USD",
        "TIMEZONE": "America/New_York",
        "TRADE_STARTS": time(0, 0, 0),
        "TRADE_ENDS": time(23, 59, 59)
    },
    {
        "ID": 16,
        "GROUP": "Commodity",
        "NAME": "Crude Oil",
        "SYMBOL": "CL=F",
        "EXCHANGE": "Yahoo",
        "PLATFORM": "Yahoo",
        "BROKER": "Yahoo",
        "CCY": "USD",
        "TIMEZONE": "America/New_York",
        "TRADE_STARTS": time(0, 0, 0),
        "TRADE_ENDS": time(23, 59, 59)
    },
    {
        "ID": 17,
        "GROUP": "Commodity",
        "NAME": "Natural Gas",
        "SYMBOL": "NG=F",
        "EXCHANGE": "Yahoo",
        "PLATFORM": "Yahoo",
        "BROKER": "Yahoo",
        "CCY": "USD",
        "TIMEZONE": "America/New_York",
        "TRADE_STARTS": time(0, 0, 0),
        "TRADE_ENDS": time(23, 59, 59)
    },
    {
        "ID": 18,
        "GROUP": "Commodity",
        "NAME": "Coffee",
        "SYMBOL": "KC=F",
        "EXCHANGE": "Yahoo",
        "PLATFORM": "Yahoo",
        "BROKER": "Yahoo",
        "CCY": "USD",
        "TIMEZONE": "America/New_York",
        "TRADE_STARTS": time(0, 0, 0),
        "TRADE_ENDS": time(23, 59, 59)
    },
    {
        "ID": 19,
        "GROUP": "Commodity",
        "NAME": "Sugar",
        "SYMBOL": "SB=F",
        "EXCHANGE": "Yahoo",
        "PLATFORM": "Yahoo",
        "BROKER": "Yahoo",
        "CCY": "USD",
        "TIMEZONE": "America/New_York",
        "TRADE_STARTS": time(0, 0, 0),
        "TRADE_ENDS": time(23, 59, 59)
    },
    {
        "ID": 20,
        "GROUP": "Commodity",
        "NAME": "Cocoa",
        "SYMBOL": "CC=F",
        "EXCHANGE": "Yahoo",
        "PLATFORM": "Yahoo",
        "BROKER": "Yahoo",
        "CCY": "USD",
        "TIMEZONE": "America/New_York",
        "TRADE_STARTS": time(0, 0, 0),
        "TRADE_ENDS": time(23, 59, 59)
    },
    {
        "ID": 21,
        "GROUP": "Commodity",
        "NAME": "Soybean",
        "SYMBOL": "ZL=F",
        "EXCHANGE": "Yahoo",
        "PLATFORM": "Yahoo",
        "BROKER": "Yahoo",
        "CCY": "USD",
        "TIMEZONE": "America/New_York",
        "TRADE_STARTS": time(0, 0, 0),
        "TRADE_ENDS": time(23, 59, 59)
    },
    {
        "ID": 22,
        "GROUP": "Commodity",
        "NAME": "Corn",
        "SYMBOL": "ZC=F",
        "EXCHANGE": "Yahoo",
        "PLATFORM": "Yahoo",
        "BROKER": "Yahoo",
        "CCY": "USD",
        "TIMEZONE": "America/New_York",
        "TRADE_STARTS": time(0, 0, 0),
        "TRADE_ENDS": time(23, 59, 59)
    },
    {
        "ID": 23,
        "GROUP": "Commodity",
        "NAME": "Cotton",
        "SYMBOL": "CT=F",
        "EXCHANGE": "Yahoo",
        "PLATFORM": "Yahoo",
        "BROKER": "Yahoo",
        "CCY": "USD",
        "TIMEZONE": "America/New_York",
        "TRADE_STARTS": time(0, 0, 0),
        "TRADE_ENDS": time(23, 59, 59)
    },
    {
        "ID": 24,
        "GROUP": "Commodity",
        "NAME": "Wheat",
        "SYMBOL": "ZW=F",
        "EXCHANGE": "Yahoo",
        "PLATFORM": "Yahoo",
        "BROKER": "Yahoo",
        "CCY": "USD",
        "TIMEZONE": "America/New_York",
        "TRADE_STARTS": time(0, 0, 0),
        "TRADE_ENDS": time(23, 59, 59)
    },
    {
        "ID": 25,
        "GROUP": "Forex",
        "NAME": "USD/BRL",
        "SYMBOL": "BRL=X",
        "EXCHANGE": "Yahoo",
        "PLATFORM": "Yahoo",
        "BROKER": "Yahoo",
        "CCY": "USD",
        "TIMEZONE": "UTC",
        "TRADE_STARTS": time(0, 0, 0),
        "TRADE_ENDS": time(23, 59, 59)
    },
    {
        "ID": 26,
        "GROUP": "Forex",
        "NAME": "EUR/USD",
        "SYMBOL": "EURUSD=X",
        "EXCHANGE": "Yahoo",
        "PLATFORM": "Yahoo",
        "BROKER": "Yahoo",
        "CCY": "USD",
        "TIMEZONE": "UTC",
        "TRADE_STARTS": time(0, 0, 0),
        "TRADE_ENDS": time(23, 59, 59)
    },
    {
        "ID": 27,
        "GROUP": "Forex",
        "NAME": "USD/JPY",
        "SYMBOL": "JPY=X",
        "EXCHANGE": "Yahoo",
        "PLATFORM": "Yahoo",
        "BROKER": "Yahoo",
        "CCY": "USD",
        "TIMEZONE": "UTC",
        "TRADE_STARTS": time(0, 0, 0),
        "TRADE_ENDS": time(23, 59, 59)
    },
    {
        "ID": 28,
        "GROUP": "Forex",
        "NAME": "GBP/USD",
        "SYMBOL": "GBPUSD=X",
        "EXCHANGE": "Yahoo",
        "PLATFORM": "Yahoo",
        "BROKER": "Yahoo",
        "CCY": "USD",
        "TIMEZONE": "UTC",
        "TRADE_STARTS": time(0, 0, 0),
        "TRADE_ENDS": time(23, 59, 59)
    },
    {
        "ID": 29,
        "GROUP": "Forex",
        "NAME": "USD/CAD",
        "SYMBOL": "CAD=X",
        "EXCHANGE": "Yahoo",
        "PLATFORM": "Yahoo",
        "BROKER": "Yahoo",
        "CCY": "USD",
        "TIMEZONE": "UTC",
        "TRADE_STARTS": time(0, 0, 0),
        "TRADE_ENDS": time(23, 59, 59)
    },
    {
        "ID": 30,
        "GROUP": "Forex",
        "NAME": "USD/AUD",
        "SYMBOL": "AUD=X",
        "EXCHANGE": "Yahoo",
        "PLATFORM": "Yahoo",
        "BROKER": "Yahoo",
        "CCY": "USD",
        "TIMEZONE": "UTC",
        "TRADE_STARTS": time(0, 0, 0),
        "TRADE_ENDS": time(23, 59, 59)
    },
    {
        "ID": 31,
        "GROUP": "Forex",
        "NAME": "USD/NZD",
        "SYMBOL": "NZD=X",
        "EXCHANGE": "Yahoo",
        "PLATFORM": "Yahoo",
        "BROKER": "Yahoo",
        "CCY": "USD",
        "TIMEZONE": "UTC",
        "TRADE_STARTS": time(0, 0, 0),
        "TRADE_ENDS": time(23, 59, 59)
    },
    {
        "ID": 32,
        "GROUP": "Forex",
        "NAME": "USD/CNY",
        "SYMBOL": "CNY=X",
        "EXCHANGE": "Yahoo",
        "PLATFORM": "Yahoo",
        "BROKER": "Yahoo",
        "CCY": "USD",
        "TIMEZONE": "UTC",
        "TRADE_STARTS": time(0, 0, 0),
        "TRADE_ENDS": time(23, 59, 59)
    },
    {
        "ID": 33,
        "GROUP": "Forex",
        "NAME": "USD/RUB",
        "SYMBOL": "RUB=X",
        "EXCHANGE": "Yahoo",
        "PLATFORM": "Yahoo",
        "BROKER": "Yahoo",
        "CCY": "USD",
        "TIMEZONE": "UTC",
        "TRADE_STARTS": time(0, 0, 0),
        "TRADE_ENDS": time(23, 59, 59)
    },
    {
        "ID": 34,
        "GROUP": "Rate",
        "NAME": "US Treasury 13-Week",
        "SYMBOL": "^IRX",
        "EXCHANGE": "Yahoo",
        "PLATFORM": "Yahoo",
        "BROKER": "Yahoo",
        "CCY": "USD",
        "TIMEZONE": "America/Chicago",
        "TRADE_STARTS": time(0, 0, 0),
        "TRADE_ENDS": time(23, 59, 59)
    },
    {
        "ID": 35,
        "GROUP": "Rate",
        "NAME": "US Treasury 5-Year",
        "SYMBOL": "^FVX",
        "EXCHANGE": "Yahoo",
        "PLATFORM": "Yahoo",
        "BROKER": "Yahoo",
        "CCY": "USD",
        "TIMEZONE": "America/Chicago",
        "TRADE_STARTS": time(0, 0, 0),
        "TRADE_ENDS": time(23, 59, 59)
    },
    {
        "ID": 36,
        "GROUP": "Rate",
        "NAME": "US Treasury 10-Year",
        "SYMBOL": "^TNX",
        "EXCHANGE": "Yahoo",
        "PLATFORM": "Yahoo",
        "BROKER": "Yahoo",
        "CCY": "USD",
        "TIMEZONE": "America/Chicago",
        "TRADE_STARTS": time(0, 0, 0),
        "TRADE_ENDS": time(23, 59, 59)
    }
]